services:
  pokemon_go_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - pokemon_go_db
  pokemon_go_db:
    image: postgres:13
    ports:
      - 5445:5432
    environment:
      POSTGRES_USER: pokemon_go_app
      POSTGRES_PASSWORD: 123
    volumes:
      - pgdata:/var/lib/postgresql/data
  pokemon_go_test_db:
    image: postgres:13
    ports:
      - 5446:5432
    environment:
      POSTGRES_USER: pokemon_go_app
      POSTGRES_PASSWORD: 123
volumes:
  pgdata:
